hifive/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),

]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('developer/', views.developer, name="developer"),
    path('communicate/', views.paging, name="paging"),
    path('communicate/<int:question_id>/', views.detail, name='detail'),
    path('communicate/question_create/', views.question_create, name='question_create'),
    path('communicate/answer_create/<int:question_id>/', views.answer_create, name='answer_create'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('exercise/', views.exercise, name="exercise"),
    path('mypage/', views.mypage, name="mypage"),
]

main/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    writer = models.CharField(max_length=20)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    writer = models.CharField(max_length=20)
    content = models.TextField()
    create_date = models.DateTimeField()

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import MinLengthValidator

class Camera(models.Model):
    date = models.DateField(null=True)
    basic_img = models.TextField(null=True)
    outline_img = models.TextField(null=True)
    joint_img = models.TextField(null=True)
    outline_area = models.IntegerField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    name = models.CharField(max_length=20, null=True)
    age = models.IntegerField(null=True)
    height = models.IntegerField(null=True)
    weight = models.IntegerField(null=True)
    device_pw = models.CharField(max_length=4, validators=[MinLengthValidator(4)], default="0000")


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/forms.py
from django import forms
from main.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

users/forms.py
from django import forms
from allauth.account.forms import SignupForm

class MyCustomSignupForm(SignupForm):
    name = forms.CharField(label='이름')
    age = forms.IntegerField(label='나이')
    height = forms.IntegerField(label='키')
    weight = forms.IntegerField(label='몸무게')
    device_pw = forms.CharField(label='기기 비밀번호(숫자 4자리)')

    def save(self, request):
        user = super(MyCustomSignupForm, self).save(request)
        user.profile.name = self.cleaned_data['name']
        user.profile.age = self.cleaned_data['age']
        user.profile.height = self.cleaned_data['height']
        user.profile.weight = self.cleaned_data['weight']
        user.profile.device_pw = self.cleaned_data['device_pw']
        user.save()
        return user

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from .forms import QuestionForm, AnswerForm
from .models import Question

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

def contact(request):
    return render(request, 'main/contact.html')

def developer(request):
    return render(request, 'main/developer.html')


def question_create(request):
    """
    질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.writer = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('main:paging')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'main/communicate_form.html', context)


def answer_create(request, question_id):
    """
    답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.writer = request.user
            answer.question = question
            answer.save()
            return redirect('main:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'main/communicate_detail.html', context)


def paging(request):
    """
    목록출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

    # 조회
    question_list = Question.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'main/communicate.html', context)


def detail(request, question_id):
    """
    내용출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'main/communicate_detail.html', context)

users/views.py
from django.shortcuts import render
from typing import List

from .models import Profile, Camera
import base64


# Create your views here.
def exercise(request):
    profile = Profile.objects.get(user=request.user)
    cameras = Camera.objects.filter(user=request.user)
    length = len(cameras)
    recent = cameras.last()
    first = cameras.first()
    context = {
        'profile': profile,
        'cameras': cameras,
        'recent': recent,
        'first': first,

    }
    return render(request, 'users/exercise.html', context)


def mypage(request):
    cameras = Camera.objects.filter(user=request.user)
    length = len(cameras)
    recent = cameras.last()
    first = cameras.first()
    context = {
        'cameras': cameras,
        'recent': recent,
        'first': first,
    }
    return render(request, 'users/mypage.html',context)

hifive/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Title -->
    <title>NUMBodySmartMirror</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'public/css/base.css' %}">


    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'public/img/favicon.ico' %}">


    <!-- DEMO CHARTS -->
    <link rel="stylesheet" href="{% static 'public/demo/chartist.css' %}">
    <link rel="stylesheet" href="{% static 'public/demo/chartist-plugin-tooltip.css' %}">

    <!-- Template -->
    <link rel="stylesheet" href="{% static 'public/graindashboard/css/graindashboard.css' %}">

</head>

<body class="has-sidebar has-fixed-sidebar-and-header">
<!-- Header -->
<header class="header bg-body">
    <nav class="navbar flex-nowrap p-0">
        <div class="navbar-brand-wrapper d-flex align-items-center col-auto">
            <!-- Logo For Mobile View -->
            <a class="navbar-brand navbar-brand-mobile" href="/">
                <img class="img-fluid w-100" src="{% static 'public/img/nbm.png' %}" alt="Graindashboard"
                     style="max-width:100%; height:auto;">
            </a>
            <!-- End Logo For Mobile View -->

            <!-- Logo For Desktop View -->
            <a class="navbar-brand navbar-brand-desktop" href="/">
                <img class="side-nav-show-on-closed" src="{% static 'public/img/nbm.png' %}" alt="Graindashboard"
                     style="width: 60px; height: auto;">
                <div class="side-nav-hide-on-closed">
                    <img class="logo-img" src="{% static 'public/img/title-logo.png' %}" alt="Graindashboard"
                         style="width: 400px; height: 150px; float: left; max-width:100%; height:auto;">
                </div>
            </a>
            <!-- End Logo For Desktop View -->
        </div>

        <div class="header-content col px-md-3">
            <div class="d-flex align-items-center">
                <!-- Side Nav Toggle -->
                <a class="js-side-nav header-invoker d-flex mr-md-2" href="#"
                   data-close-invoker="#sidebarClose"
                   data-target="#sidebar"
                   data-target-wrapper="body">
                    <i class="gd-align-left"></i>
                </a>
                <!-- End Side Nav Toggle -->

                {% if user.is_authenticated %}
                    <!-- User Avatar -->
                    <div class="dropdown mx-3 dropdown ml-2">
                        <a id="profileMenuInvoker" class="header-complex-invoker" href="#" aria-controls="profileMenu"
                           aria-haspopup="true" aria-expanded="false" data-unfold-event="click"
                           data-unfold-target="#profileMenu" data-unfold-type="css-animation" data-unfold-duration="300"
                           data-unfold-animation-in="fadeIn" data-unfold-animation-out="fadeOut">
                            <!--img class="avatar rounded-circle mr-md-2" src="#" alt="John Doe"-->
                            <span class="mr-md-2 avatar-placeholder">J</span>
                            <span class="d-none d-md-block">{{ request.user }}</span>
                            <i class="gd-angle-down d-none d-md-block ml-2"></i>
                        </a>

                        <ul id="profileMenu"
                            class="unfold unfold-user unfold-light unfold-top unfold-centered position-absolute pt-2 pb-1 mt-4 unfold-css-animation unfold-hidden fadeOut"
                            aria-labelledby="profileMenuInvoker" style="animation-duration: 300ms;">
                            <li class="unfold-item">
                                <a class="unfold-link d-flex align-items-center text-nowrap"
                                   href="{% url 'users:mypage' %}">
                    <span class="unfold-item-icon mr-3">
                      <i class="gd-user"></i>
                    </span>
                                    My Profile
                                </a>
                            </li>
                            <li class="unfold-item unfold-item-has-divider">
                                <a class="unfold-link d-flex align-items-center text-nowrap"
                                   href="{% url 'account_logout' %}">
                    <span class="unfold-item-icon mr-3">
                      <i class="gd-power-off"></i>
                    </span>
                                    LogOut
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End User Avatar -->
                    </div>
                {% else %}
                {% endif %}
        </div>
    </nav>
</header>
<!-- End Header -->

{% include 'shared/navbar.html' %}
{% block content %}

{% endblock %}
{% include 'shared/footer.html' %}

</div>
</main>


<script src="{% static 'public/graindashboard/js/graindashboard.js' %}"></script>
<script src="{% static 'public/graindashboard/js/graindashboard.vendor.js' %}"></script>

<!-- DEMO CHARTS -->
<script src="{% static 'public/demo/resizeSensor.js' %}"></script>
<script src="{% static 'public/demo/chartist.js' %}"></script>
<script src="{% static 'public/demo/chartist-plugin-tooltip.js' %}"></script>
<script src="{% static 'public/demo/gd.chartist-area.js' %}"></script>
<script src="{% static 'public/demo/gd.chartist-bar.js' %}"></script>
<script src="{% static 'public/demo/gd.chartist-donut.js' %}"></script>
<script>
    $.GDCore.components.GDChartistArea.init('.js-area-chart');
    $.GDCore.components.GDChartistBar.init('.js-bar-chart');
    $.GDCore.components.GDChartistDonut.init('.js-donut-chart');
</script>
</body>
</html>

hifive/templates/shared/footer.html
{% load static %}
<!-- Footer -->
<head>
    <link rel="stylesheet" href="{% static 'public/css/footer.css' %}">
</head>

<footer class="small p-3 px-md-4 mt-auto" id="footer">
    <img class="footer-img" src="{% static 'public/img/nbm_tail.png' %}" >

    <div class="row justify-content-between">
        <div class="col-lg text-center text-lg-left mb-3 mb-lg-0">
            <ul class="list-dot list-inline mb-0">
                <li class="list-dot-item list-inline-item mr-lg-2"><a class="link-dark" href="{% url 'main:developer' %}">Developer</a></li>
                <li class="list-dot-item list-inline-item mr-lg-2"><a class="link-dark" href="{% url 'main:contact' %}">Contact us</a></li>

            </ul>
        </div>
        <div class="col-lg text-center mb-3 mb-lg-0">
            <ul class="list-inline mb-0">
                <li class="list-inline-item mx-2"><a class="link-muted" href="https://github.com/dddooo9/hifive"><i class="gd-github"></i></a></li>
            </ul>
        </div>
        <div class="col-lg text-center text-lg-right">
            &copy; 2021 hifive. All Rights Reserved.
        </div>
    </div>
</footer>
<!-- End Footer -->

hifive/templates/shared/navbar.html
{% load static %}
<main class="main">
    <!-- Sidebar Nav -->
    <aside id="sidebar" class="js-custom-scroll side-nav">
        <ul id="sideNav" class="side-nav-menu side-nav-menu-top-level mb-0">
            {% if user.is_authenticated %}
            <!-- Title -->
            <li class="sidebar-heading h6">Private Service</li>
            <!-- End Title -->

            <!-- Dashboard  active 삭제-->
            <li class="side-nav-menu-item">
                <a class="side-nav-menu-link media align-items-center" href="{% url 'users:exercise' %}">
              <span class="side-nav-menu-icon d-flex mr-3">
                <i class="gd-dashboard"></i>
              </span>
                    <span class="side-nav-fadeout-on-closed media-body">운동 기록</span>
                </a>
            </li>
            <!-- End Dashboard -->

            <!-- Documentation -->
            <li class="side-nav-menu-item">
                <a class="side-nav-menu-link media align-items-center" href="{% url 'users:mypage' %}">
              <span class="side-nav-menu-icon d-flex mr-3">
                <i class="gd-file"></i>
              </span>
                    <span class="side-nav-fadeout-on-closed media-body">My page</span>
                </a>
            </li>
            <!-- End Documentation -->
            {% else %}
            {% endif %}

            <!-- Title -->
            <li class="sidebar-heading h6">catalog</li>
            <!-- End Title -->

            <!-- Users -->
            <li class="side-nav-menu-item side-nav-has-menu">
                <a class="side-nav-menu-link media align-items-center" href="#"
                   data-target="#subUsers">
                  <span class="side-nav-menu-icon d-flex mr-3">
                    <i class="gd-user"></i>
                  </span>
                    <span class="side-nav-fadeout-on-closed media-body">Users</span>
                    <span class="side-nav-control-icon d-flex">
                <i class="gd-angle-right side-nav-fadeout-on-closed"></i>
              </span>
                    <span class="side-nav__indicator side-nav-fadeout-on-closed"></span>
                </a>

                <!-- Users: subUsers -->
                <ul id="subUsers" class="side-nav-menu side-nav-menu-second-level mb-0">
                    {% if user.is_authenticated %}
                        <li class="side-nav-menu-item">
                            <a class="side-nav-menu-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="side-nav-menu-item">
                            <a class="side-nav-menu-link" href="{% url 'account_signup' %}">Signup</a>
                        </li>
                        <li class="side-nav-menu-item">
                            <a class="side-nav-menu-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
                <!-- End Users: subUsers -->
            </li>
            <!-- End Users -->

            <!-- Communicate -->
            <li class="side-nav-menu-item">
                <a class="side-nav-menu-link media align-items-center" href="{% url 'main:paging' %}">
              <span class="side-nav-menu-icon d-flex mr-3">
                <i class="gd-file"></i>
              </span>
                    <span class="side-nav-fadeout-on-closed media-body">Communicate</span>
                </a>
            </li>
            <!-- End Communicate -->

        </ul>
    </aside>
    <!-- End Sidebar Nav -->

main/templates/main/communicate.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}
{% block content %}
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/communicate.css' %}">
</head>
<table class="table">
    <h1>Communicate</h1>
    <thead>
    <tr class="thead-dark">
        <th>number</th>
        <th>Context</th>
        <th>Writer</th>
        <th>Date</th>
    </tr>
    </thead>

    <tbody>
    {% if question_list %}
        {% for question in question_list %}
            <tr>
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    {{ question_list.paginator.count| sub:question_list.start_index| sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    <a href="{% url 'main:detail' question.id %}">{{ question.subject }}</a>
                    {% if question.answer_set.count > 0 %}
                        <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ question.writer }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
    {% endif %}

    </tbody>
</table>

<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝-->

<br>
{% if user.is_authenticated %}
<a  href="{% url 'main:question_create' %}" class="btn btn-primary">질문 등록하기</a>
{% else %}
{% endif %}
<hr color="gray" class="bottom-line" align="center">




{% endblock %}

main/templates/main/communicate_detail.html
{% extends 'base.html' %}


{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{#    #}
    <form action="{% url 'main:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>

        <input type="submit" value="답변등록" class="btn btn-primary">
        {% else %}
        {% endif %}
    </form>


</div>
{% endblock %}

main/templates/main/communicate_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static '' %}">
</head>

<section class="main">
    <header><h1>Communicate</h1></header><br>
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post" class="post-form my-3">
            {% csrf_token %}
             <!-- 오류표시 Start -->
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea class="form-control" name="content"
                          id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            {% if user.is_authenticated %}
            <button type="submit" class="btn btn-primary">저장하기</button>
            {% else %}
            {% endif %}

        </form>
    </div>
</section>

{% endblock %}

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
</head>
<section class="main contact">
    <header><h1>Contact us</h1></header><br>
    <section>
        <table class="table">
            <tbody>
            <tr>
                <td>Tel</td>
                <td>02 - 0000 - 0000</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>서울특별시 </td>
            </tr>
            <tr>
                <td>E-mail</td>
                <td>0000000@gmail.com</td>
            </tr>
            </tbody>
        </table>
    </section>
</section>

{% endblock %}

main/templates/main/developer.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/developer.css' %}">
</head>

<section class="main dev">
    <header><h1>Developer</h1></header><br>
    <section>
        <table class="table">
            <tbody>
            <tr>
                <td>Leader</td>
                <td>이도은 </td>
            </tr>
            <tr>
                <td>Web</td>
                <td>박지혜, 이지유, 임도연</td>
            </tr>
            <tr>
                <td>HW</td>
                <td>안상연, 이도은, 임도연</td>
            </tr>
            <tr>
                <td>Develop term</td>
                <td>2021.03 ~ 2021.11</td>
            </tr>
            <tr>
                <td>Web Git Link</td>
                <td><a href="https://github.com/dddooo9/hifive"  target="_blank" >https://github.com/dddooo9/hifive</a></td>
            </tr>
            </tbody>
        </table>
    </section>
</section>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<div>
    <div class="container my-3">
        <img class="banner_top" src = "{% static 'img/nbm_cover_photo_1.png' %}"  style="width: 100%; height: auto">
        <h1 class="title-text" style="font-size:50px">눈바디 스마트미러에 오신 것을 환영합니다!</h1>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="mirror_img" src ="https://funshop.akamaized.net/abroad/027/13713/Ayi%20Smart%20mirror%203_1.jpg" alt="first slide" style="width: 100%; height: auto">
                </div>
                <div class="carousel-item">
                    <img class="mirror_img" src="https://t1.daumcdn.net/liveboard/bizion/cd26d7d0580e4b848a3e887c550030e9.JPG" alt="Second slide" style="width: 100%; height: auto">
                </div>
                <div class="carousel-item">
                    <img class="mirror_img" src="https://image.ajunews.com/content/image/2020/07/12/20200712172022555148.png"alt="Third slide" style="width: 100%; height: auto">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="introduction">
        <div>
            <div class="introduction_top">
                <h1 class="introduction_title">눈바디 스마트미러란</h1>
            </div>
            <div class="introduction_content">
                <img src="https://funshop.akamaized.net/abroad/027/13713/Ayi%20Smart%20mirror%203_1.jpg" alt="..." class="introduction_img" style="width: 60%; height: auto">
                <h2>스마트미러는 단순한 거울이 아닙니다. 언제든 거울로써 활용이 가능한 기능 제공됨과 동시에 눈바디를 확인할 수 있습니다.
                    집에서 언제든지 간편하게 체형을 측정하고, 분석 정보를 받아볼 수 있습니다.
                    스마트미러는 웹페이지로 연결되어 <span style="color:mediumblue">체형 정보, 추천 운동, 운동 캘린더</span>등의 정보를 제공합니다.
                    원할때 편리하게 체형 정보를 확인해보세요.
                </h2>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/page.css' %}">
<div class="page-main">
    <h1>My page</h1>
    <hr>
    <h2 class="Profile">{{request.user}}님 회원정보</h2>
    <div style="float:right">
        <div class="physique">
            <h5>최초체형</h5>
            <img src="https://postfiles.pstatic.net/MjAyMTA3MzFfMjYy/MDAxNjI3NzAwOTI2OTYw.Xajzr6Xx4ps7lgW6qpG0FBamkaI_Bkdo1j3GQsgQ2Jog.Zuzbx3MVNn90btzG8fmWWpOQBbNnORFq7wfavaWeMKog.JPEG.skawjdska235/%EC%B2%B4%ED%98%95.jpg?type=w773">
        </div>
        <div class ="posture">
            <h5>최초자세</h5>
            <img src="https://postfiles.pstatic.net/MjAyMTA3MzFfMzMg/MDAxNjI3NzAwOTI2OTY1.n-wWJM4HF1Ej9F3fLPCbKr_ykppOaPgnkA15dgVCgRMg.jn6H4d-iCEJmLdrw7RweRUAFFSMMperIKjBKzN87Lukg.JPEG.skawjdska235/%EC%9E%90%EC%84%B8.jpg?type=w773">
        </div>

        <div style="float:left" >
            <table class="table">
                <thead>
                <tr>

                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>ID</td>
                    <td>{{ request.user }}</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Singup Date</td>
                    <td>{{ request.user.date_joined }}</td>
                </tr>
                <tr>
                    <td>Height</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
    <img class="nbm_tail" src="{% static 'img\nbm_tail.png' %}">
{% endblock%}